openapi: 3.0.1
info:
  title: ICommerce brand Service
  version: 0.0.1
servers:
  - url: ''
paths:
  /authenticate/login:
    post:
      description: Login
      operationId: login
      tags:
        - authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: login success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /authenticate/refresh:
    post:
      description: Refresh access token
      operationId: refreshToken
      tags:
        - authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string

    RefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]
